# TargetedSurprise 模型配置
model:
  d_model: 64  # 模型维度
  n_targets: 8  # 目标数量
  decay_threshold: 0.95  # 衰减阈值
  surprise_threshold: 0.5  # 惊喜检测阈值

training:
  batch_size: 32
  learning_rate: 1e-4
  max_seq_len: 1024